### ISSUE TITLE
Possible bug detected by San Jose State University students

### ISSUE THREAD

**Issue by LennartFr** [IBM/auction-events#5]
Emit events from Blockchain Platform V2.0
It is working fine with some modifications required while following the documentation. 

delete app-admin in wallet directory
add below lines in  mychannel_auction_profile.json  

"channels": {"mychannel": {}}
Edit below lines in invoke-emit.js to pass the IP address of the peer present in the  mychannel_auction_profile.json  : 
Line #57:   const channel_event_hub = channel.getChannelEventHub('173.193.75.36:31584');
Line #146: let event_hub = channel.newChannelEventHub('173.193.75.36:31584');
------------------------------------------------------------------------------------------

**Comment by ljbennett62** [comment]
@LennartFr - I have updated the repo - and removed the hard coded IP for the Peer.  I added instructions to insert the IP in the config.json file so it is unique to every user. FYI - we are told to ignore the error `error: [Client.js]: Channel note found for name my channel`. This is not a real error and the the Blockchain BU is working on a fix to stop having this error show up.  Code should be fine now - please try it out.
