### ISSUE TITLE
Help with the UI

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [IBM/auction-events#8]
Hi, how about, excuse me you could give a small example of a given UI that I can not think of how to run this on a localhost to interact with the browser

**Comment by ljbennett62** [comment]
Perhaps you can create a UI where you have a list of users with the ability to select transactions (e.g. bid, sell) and then show the results of the transaction which emits an event in a different part of the screen. So someone can interface with teh browser by selecting a user and then selecting a transaction and then showing the event trigger results.
